version: "3.7"
services:
  barcodekeeper:
    build: .
    image: barcodekeeper:local
    entrypoint: /bin/sh
    env_file: ./ENVFILE.env
    devices:
      - "/dev/gpiomem"
    volumes:
      - ./data/:/data
      - ./input_barcode.sh:/usr/local/bin/input_barcode
